### ISSUE TITLE
Add a "NoSuchElementException" for iteration

### ISSUE THREAD

**Issue by UtkaK18** [meetkalariya/jmonkeyengineFall2024#11]
**Describe the technical debt**
The technical debt arises from the next() method not throwing a NoSuchElementException when no elements remain, violating the Java Iterator contract. This can lead to API non-compliance, bugs from unexpected null values, and increased maintenance complexity. Fixing it requires modifying next() to throw the exception, ensuring proper iteration behavior.

Proposed Solution:
Solution: Modify next() to throw NoSuchElementException when no more elements are present, resolving the technical debt and improving system robustness.

File Location:
jme3-core/src/main/java/com/jme3/shader/bufferobject/DirtyRegionsIterator.java

**Comment by meetkalariya** [comment]
Group 8 is assigned jme3-desktop not jme3-core.

**Comment by meetkalariya** [comment]
Closing the issue as this is not the specified directory.
